// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotorcycleLicenseTrainingAPI.Model;

#nullable disable

namespace MotorcycleLicenseTrainingAPI.Migrations
{
    [DbContext(typeof(MotorcycleLicenseTrainingContext))]
    partial class MotorcycleLicenseTrainingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MockExamQuestion", b =>
                {
                    b.Property<int>("MockExamId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("MockExamId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("MockExamQuestion");

                    b.HasData(
                        new
                        {
                            MockExamId = 9,
                            QuestionId = 1
                        },
                        new
                        {
                            MockExamId = 10,
                            QuestionId = 1
                        },
                        new
                        {
                            MockExamId = 12,
                            QuestionId = 1
                        },
                        new
                        {
                            MockExamId = 17,
                            QuestionId = 1
                        },
                        new
                        {
                            MockExamId = 18,
                            QuestionId = 1
                        },
                        new
                        {
                            MockExamId = 19,
                            QuestionId = 1
                        },
                        new
                        {
                            MockExamId = 20,
                            QuestionId = 1
                        },
                        new
                        {
                            MockExamId = 10,
                            QuestionId = 2
                        },
                        new
                        {
                            MockExamId = 12,
                            QuestionId = 2
                        },
                        new
                        {
                            MockExamId = 17,
                            QuestionId = 2
                        },
                        new
                        {
                            MockExamId = 18,
                            QuestionId = 2
                        },
                        new
                        {
                            MockExamId = 19,
                            QuestionId = 2
                        },
                        new
                        {
                            MockExamId = 20,
                            QuestionId = 2
                        },
                        new
                        {
                            MockExamId = 12,
                            QuestionId = 3
                        },
                        new
                        {
                            MockExamId = 17,
                            QuestionId = 3
                        },
                        new
                        {
                            MockExamId = 18,
                            QuestionId = 3
                        },
                        new
                        {
                            MockExamId = 19,
                            QuestionId = 3
                        },
                        new
                        {
                            MockExamId = 20,
                            QuestionId = 3
                        },
                        new
                        {
                            MockExamId = 12,
                            QuestionId = 4
                        },
                        new
                        {
                            MockExamId = 17,
                            QuestionId = 4
                        },
                        new
                        {
                            MockExamId = 18,
                            QuestionId = 4
                        },
                        new
                        {
                            MockExamId = 19,
                            QuestionId = 4
                        },
                        new
                        {
                            MockExamId = 20,
                            QuestionId = 4
                        },
                        new
                        {
                            MockExamId = 12,
                            QuestionId = 5
                        },
                        new
                        {
                            MockExamId = 17,
                            QuestionId = 5
                        },
                        new
                        {
                            MockExamId = 18,
                            QuestionId = 5
                        },
                        new
                        {
                            MockExamId = 19,
                            QuestionId = 5
                        },
                        new
                        {
                            MockExamId = 20,
                            QuestionId = 5
                        },
                        new
                        {
                            MockExamId = 17,
                            QuestionId = 11
                        },
                        new
                        {
                            MockExamId = 18,
                            QuestionId = 11
                        },
                        new
                        {
                            MockExamId = 19,
                            QuestionId = 11
                        },
                        new
                        {
                            MockExamId = 20,
                            QuestionId = 11
                        },
                        new
                        {
                            MockExamId = 17,
                            QuestionId = 12
                        },
                        new
                        {
                            MockExamId = 18,
                            QuestionId = 12
                        },
                        new
                        {
                            MockExamId = 19,
                            QuestionId = 12
                        },
                        new
                        {
                            MockExamId = 20,
                            QuestionId = 12
                        },
                        new
                        {
                            MockExamId = 17,
                            QuestionId = 13
                        },
                        new
                        {
                            MockExamId = 18,
                            QuestionId = 13
                        },
                        new
                        {
                            MockExamId = 19,
                            QuestionId = 13
                        },
                        new
                        {
                            MockExamId = 20,
                            QuestionId = 13
                        },
                        new
                        {
                            MockExamId = 17,
                            QuestionId = 14
                        },
                        new
                        {
                            MockExamId = 18,
                            QuestionId = 14
                        },
                        new
                        {
                            MockExamId = 19,
                            QuestionId = 14
                        },
                        new
                        {
                            MockExamId = 20,
                            QuestionId = 14
                        },
                        new
                        {
                            MockExamId = 17,
                            QuestionId = 15
                        },
                        new
                        {
                            MockExamId = 18,
                            QuestionId = 15
                        },
                        new
                        {
                            MockExamId = 19,
                            QuestionId = 15
                        },
                        new
                        {
                            MockExamId = 20,
                            QuestionId = 15
                        },
                        new
                        {
                            MockExamId = 20,
                            QuestionId = 16
                        },
                        new
                        {
                            MockExamId = 20,
                            QuestionId = 17
                        });
                });

            modelBuilder.Entity("MotorcycleLicenseTrainingAPI.Model.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerId"), 1L, 1);

                    b.Property<string>("AnswerText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answer");

                    b.HasData(
                        new
                        {
                            AnswerId = 5,
                            AnswerText = "Được khách hàng, xã hội tôn trọng; được đồng nghiệp quý mến, giúp đỡ; được doanh nghiệp tin dùng và đóng góp nhiều cho xã hội.",
                            IsCorrect = false,
                            QuestionId = 1
                        },
                        new
                        {
                            AnswerId = 6,
                            AnswerText = "Thu hút được khách hàng, góp phần quan trọng trong xây dựng thương hiệu, kinh doanh có hiệu quả cao.",
                            IsCorrect = false,
                            QuestionId = 1
                        },
                        new
                        {
                            AnswerId = 7,
                            AnswerText = "Cả ý 1 và ý 2.",
                            IsCorrect = true,
                            QuestionId = 1
                        },
                        new
                        {
                            AnswerId = 9,
                            AnswerText = "Thực hiện nghiêm chỉnh những nội dung hợp đồng giữa chủ phương tiện với chủ hàng trong việc vận chuyển và bảo quản hàng hóa trong quá trình vận chuyển; không chở hàng cấm, không xếp hàng quá trọng tải của xe, quá trọng tải cho phép của cầu, đường; khi vận chuyển hàng quá khổ, quá tải, hàng nguy hiểm, hàng siêu trường, siêu trọng phải có giấy phép.",
                            IsCorrect = true,
                            QuestionId = 2
                        },
                        new
                        {
                            AnswerId = 11,
                            AnswerText = "Thực hiện nghiêm chỉnh những nội dung hợp đồng giữa chủ hàng với khách hàng trong việc vận chuyển và bảo quản hàng hóa trong quá trình vận chuyển; trong trường hợp cần thiết có thể xếp hàng quá trọng tải của xe, quá trọng tải cho phép của cầu theo yêu cầu của chủ hàng; khi vận chuyển hàng quá khổ, quá tải, hàng nguy hiểm, hàng siêu trường, siêu trọng phải được chủ hàng cho phép.",
                            IsCorrect = false,
                            QuestionId = 2
                        },
                        new
                        {
                            AnswerId = 12,
                            AnswerText = "Phải yêu quý xe, quản lý và sử dụng xe tốt; bảo dưỡng xe đúng định kỳ; thực hành tiết kiệm vật tư, nhiên liệu; luôn tu dưỡng bản thân, có lối sống lành mạnh, tác phong làm việc công nghiệp.",
                            IsCorrect = false,
                            QuestionId = 3
                        },
                        new
                        {
                            AnswerId = 14,
                            AnswerText = "Nắm vững các quy định của pháp luật, tự giác chấp hành pháp luật, lái xe an toàn; coi hành khách như người thân, là đối tác tin cậy; có ý thức tổ chức kỷ luật và xây dựng doanh nghiệp vững mạnh; có tinh thần hợp tác, tương trợ, giúp đỡ đồng nghiệp.",
                            IsCorrect = false,
                            QuestionId = 3
                        },
                        new
                        {
                            AnswerId = 15,
                            AnswerText = "Cả ý 1 và ý 2.",
                            IsCorrect = true,
                            QuestionId = 3
                        },
                        new
                        {
                            AnswerId = 16,
                            AnswerText = "Kiểm tra các điều kiện bảo đảm an toàn của xe sau khi khởi hành; có trách nhiệm lái xe thật nhanh khi chậm giờ của",
                            IsCorrect = false,
                            QuestionId = 4
                        },
                        new
                        {
                            AnswerId = 17,
                            AnswerText = "Kiểm tra các điều kiện bảo đảm an toàn của xe trước khi khởi hành; có thái độ văn minh, lịch sự, hướng dẫn hành khách ngồi đúng nơi quy định; kiểm tra việc sắp xếp, chằng buộc hành lý, bảo đảm an toàn.",
                            IsCorrect = false,
                            QuestionId = 4
                        },
                        new
                        {
                            AnswerId = 18,
                            AnswerText = "Cả ba biển.",
                            IsCorrect = false,
                            QuestionId = 11
                        },
                        new
                        {
                            AnswerId = 19,
                            AnswerText = "Biển 2 và 3.",
                            IsCorrect = false,
                            QuestionId = 11
                        },
                        new
                        {
                            AnswerId = 20,
                            AnswerText = "Biển 1 và 3.",
                            IsCorrect = false,
                            QuestionId = 11
                        },
                        new
                        {
                            AnswerId = 21,
                            AnswerText = "Biển 1 và 2.",
                            IsCorrect = true,
                            QuestionId = 11
                        },
                        new
                        {
                            AnswerId = 22,
                            AnswerText = "Phần mặt đường và lề đường.",
                            IsCorrect = false,
                            QuestionId = 12
                        },
                        new
                        {
                            AnswerId = 23,
                            AnswerText = "Phần đường xe chạy.",
                            IsCorrect = true,
                            QuestionId = 12
                        },
                        new
                        {
                            AnswerId = 24,
                            AnswerText = "Phần đường xe cơ giới.",
                            IsCorrect = false,
                            QuestionId = 12
                        },
                        new
                        {
                            AnswerId = 25,
                            AnswerText = "Là một phần của phần đường xe chạy được chia theo chiều dọc của đường, sử dụng cho xe chạy.",
                            IsCorrect = false,
                            QuestionId = 13
                        },
                        new
                        {
                            AnswerId = 26,
                            AnswerText = "Là một phần của phần đường xe chạy được chia theo chiều dọc của đường, có bề rộng đủ cho xe chạy an toàn.",
                            IsCorrect = true,
                            QuestionId = 13
                        },
                        new
                        {
                            AnswerId = 27,
                            AnswerText = "Là một phần của phần đường xe chạy được chia theo chiều dọc của đường, có đủ bề rộng cho xe ô tô chạy an toàn.",
                            IsCorrect = false,
                            QuestionId = 13
                        },
                        new
                        {
                            AnswerId = 29,
                            AnswerText = "Là khoảng trống có kích thước giới hạn về chiều cao, chiều rộng của đường, cầu, bến phà, hầm đường bộ để các xe kể cả hàng hóa xếp trên xe đi qua được an toàn.",
                            IsCorrect = true,
                            QuestionId = 14
                        },
                        new
                        {
                            AnswerId = 32,
                            AnswerText = "Là khoảng trống có kích thước giới hạn về chiều rộng của đường, cầu, bến phà, hầm trên đường bộ để các xe kể cả hàng hóa xếp trên xe đi qua được an toàn.",
                            IsCorrect = false,
                            QuestionId = 14
                        },
                        new
                        {
                            AnswerId = 33,
                            AnswerText = "Là khoảng trống có kích thước giới hạn về chiều cao của cầu, bến phà, hầm trên đường bộ để các xe đi qua được an toàn.",
                            IsCorrect = false,
                            QuestionId = 14
                        },
                        new
                        {
                            AnswerId = 34,
                            AnswerText = "Là bộ phận của đường để ngăn cách không cho các loại xe vào những nơi không được phép.",
                            IsCorrect = false,
                            QuestionId = 15
                        },
                        new
                        {
                            AnswerId = 35,
                            AnswerText = "Là bộ phận của đường để phân tách phần đường xe chạy và hành lang an toàn giao thông.",
                            IsCorrect = false,
                            QuestionId = 15
                        },
                        new
                        {
                            AnswerId = 36,
                            AnswerText = "Là bộ phận của đường để phân chia mặt đường thành hai chiều xe chạy riêng biệt hoặc để phân chia phần đường của xe cơ giới và xe thô sơ.",
                            IsCorrect = true,
                            QuestionId = 15
                        },
                        new
                        {
                            AnswerId = 37,
                            AnswerText = "Có biện pháp bảo vệ tính mạng, sức khỏe, tài sản của hành khách đi xe, giữ gìn trật tự, vệ sinh trong xe; đóng cửa lên xuống của xe trước và trong khi xe chạy.",
                            IsCorrect = false,
                            QuestionId = 4
                        },
                        new
                        {
                            AnswerId = 38,
                            AnswerText = "Cả ý 2 và ý 3.",
                            IsCorrect = true,
                            QuestionId = 4
                        },
                        new
                        {
                            AnswerId = 39,
                            AnswerText = "Là sự hiểu biết và chấp hành nghiêm chỉnh pháp luật về giao thông; là ý thức trách nhiệm với cộng đồng khi tham gia giao thông.",
                            IsCorrect = false,
                            QuestionId = 5
                        },
                        new
                        {
                            AnswerId = 40,
                            AnswerText = "Là ứng xử có văn hóa, có tình yêu thương con người trong các tình huống không may xảy ra khi tham gia giao thông.",
                            IsCorrect = false,
                            QuestionId = 5
                        },
                        new
                        {
                            AnswerId = 41,
                            AnswerText = "Cả ý 1 và ý 2.",
                            IsCorrect = true,
                            QuestionId = 5
                        },
                        new
                        {
                            AnswerId = 42,
                            AnswerText = "Biển báo nguy hiểm.",
                            IsCorrect = false,
                            QuestionId = 16
                        },
                        new
                        {
                            AnswerId = 43,
                            AnswerText = "Biển báo cấm.",
                            IsCorrect = true,
                            QuestionId = 16
                        },
                        new
                        {
                            AnswerId = 44,
                            AnswerText = "Biển báo hiệu lệnh.",
                            IsCorrect = false,
                            QuestionId = 16
                        },
                        new
                        {
                            AnswerId = 45,
                            AnswerText = "Biển báo chỉ dẫn.",
                            IsCorrect = false,
                            QuestionId = 16
                        },
                        new
                        {
                            AnswerId = 46,
                            AnswerText = "Biển báo nguy hiểm.",
                            IsCorrect = true,
                            QuestionId = 17
                        },
                        new
                        {
                            AnswerId = 47,
                            AnswerText = "Biển báo cấm.",
                            IsCorrect = false,
                            QuestionId = 17
                        },
                        new
                        {
                            AnswerId = 48,
                            AnswerText = "Biển báo hiệu lệnh.",
                            IsCorrect = false,
                            QuestionId = 17
                        },
                        new
                        {
                            AnswerId = 49,
                            AnswerText = "Biển báo chỉ dẫn.",
                            IsCorrect = false,
                            QuestionId = 17
                        });
                });

            modelBuilder.Entity("MotorcycleLicenseTrainingAPI.Model.ApplicationUsers", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "77c46877-537a-4637-bafe-b76b21a2f56e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d7cb30fa-91dd-4ff1-b4ec-a449d53f9683",
                            CreatedAt = new DateTime(2025, 3, 25, 0, 4, 42, 607, DateTimeKind.Unspecified).AddTicks(9841),
                            Email = "demo11@gmail.com",
                            EmailConfirmed = false,
                            FullName = "string",
                            LockoutEnabled = false,
                            NormalizedUserName = "DEMO11@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAENcEUydoUtT/B7gQw9O0TMdMvVZ11kOL7BXsa428YPOG84sJRcW1fcOTuYyN+xzmFQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "455c6853-6a45-40a9-9539-310166f8cfab",
                            TwoFactorEnabled = false,
                            UserName = "demo11@gmail.com"
                        });
                });

            modelBuilder.Entity("MotorcycleLicenseTrainingAPI.Model.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Biển báo cấm",
                            Type = "traffic_sign"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Biển hiệu lệnh",
                            Type = "traffic_sign"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Biển chỉ dẫn",
                            Type = "traffic_sign"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Biển báo nguy hiểm và cảnh báo",
                            Type = "traffic_sign"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Biển phụ",
                            Type = "traffic_sign"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Khái niệm và quy tắc",
                            ImageUrl = "https://png.pngtree.com/png-vector/20220925/ourmid/pngtree-a-man-explains-list-of-rule-guidelines-png-image_6212794.png",
                            Type = "theory"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Văn hóa và đạo đức lái xe",
                            ImageUrl = "https://trungtamanhngu.net/wp-content/uploads/2023/04/3.png",
                            Type = "theory"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Kỹ thuật lái xe",
                            ImageUrl = "https://lambanglaixe.vn/wp-content/uploads/2017/12/logo-745x800.png",
                            Type = "theory"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Biển báo đường bộ",
                            ImageUrl = "https://bizweb.dktcdn.net/thumb/grande/100/352/036/products/bien-bao-410.jpg?v=1600845714683",
                            Type = "theory"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Sa hình",
                            ImageUrl = "https://img.onthibanglaixe.net/blog/2023/5/kich-thuoc-vong-so-8-1688134433403.jpg",
                            Type = "theory"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Cảnh báo",
                            ImageUrl = "https://cdn-icons-png.flaticon.com/512/1410/1410040.png",
                            Type = "theory"
                        });
                });

            modelBuilder.Entity("MotorcycleLicenseTrainingAPI.Model.MockExam", b =>
                {
                    b.Property<int>("MockExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MockExamId"), 1L, 1);

                    b.Property<DateTime?>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsPassed")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalScore")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MockExamId");

                    b.HasIndex("UserId");

                    b.ToTable("MockExam");

                    b.HasData(
                        new
                        {
                            MockExamId = 9,
                            ExamDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPassed = true,
                            Status = "not_started",
                            TotalScore = 90,
                            UserId = "77c46877-537a-4637-bafe-b76b21a2f56e"
                        },
                        new
                        {
                            MockExamId = 10,
                            ExamDate = new DateTime(2025, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPassed = false,
                            Status = "not_started",
                            TotalScore = 75,
                            UserId = "77c46877-537a-4637-bafe-b76b21a2f56e"
                        },
                        new
                        {
                            MockExamId = 11,
                            ExamDate = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPassed = true,
                            Status = "not_started",
                            TotalScore = 80,
                            UserId = "77c46877-537a-4637-bafe-b76b21a2f56e"
                        },
                        new
                        {
                            MockExamId = 12,
                            ExamDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPassed = false,
                            Status = "completed",
                            TotalScore = 1,
                            UserId = "77c46877-537a-4637-bafe-b76b21a2f56e"
                        },
                        new
                        {
                            MockExamId = 13,
                            ExamDate = new DateTime(2025, 3, 24, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPassed = true,
                            Status = "not_started",
                            TotalScore = 85,
                            UserId = "77c46877-537a-4637-bafe-b76b21a2f56e"
                        },
                        new
                        {
                            MockExamId = 14,
                            ExamDate = new DateTime(2025, 3, 25, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            IsPassed = false,
                            Status = "not_started",
                            TotalScore = 60,
                            UserId = "77c46877-537a-4637-bafe-b76b21a2f56e"
                        },
                        new
                        {
                            MockExamId = 15,
                            ExamDate = new DateTime(2025, 3, 24, 21, 41, 21, 56, DateTimeKind.Unspecified).AddTicks(2617),
                            IsPassed = false,
                            Status = "not_started",
                            TotalScore = -1,
                            UserId = "77c46877-537a-4637-bafe-b76b21a2f56e"
                        },
                        new
                        {
                            MockExamId = 16,
                            ExamDate = new DateTime(2025, 3, 24, 21, 44, 19, 492, DateTimeKind.Unspecified).AddTicks(969),
                            IsPassed = false,
                            Status = "not_started",
                            TotalScore = -1,
                            UserId = "77c46877-537a-4637-bafe-b76b21a2f56e"
                        },
                        new
                        {
                            MockExamId = 17,
                            ExamDate = new DateTime(2025, 3, 25, 6, 32, 8, 496, DateTimeKind.Unspecified).AddTicks(8371),
                            IsPassed = false,
                            Status = "not_started",
                            TotalScore = -1,
                            UserId = "77c46877-537a-4637-bafe-b76b21a2f56e"
                        },
                        new
                        {
                            MockExamId = 18,
                            ExamDate = new DateTime(2025, 3, 25, 6, 32, 8, 499, DateTimeKind.Unspecified).AddTicks(5312),
                            IsPassed = false,
                            Status = "completed",
                            TotalScore = 1,
                            UserId = "77c46877-537a-4637-bafe-b76b21a2f56e"
                        },
                        new
                        {
                            MockExamId = 19,
                            ExamDate = new DateTime(2025, 3, 25, 7, 46, 56, 492, DateTimeKind.Unspecified).AddTicks(5216),
                            IsPassed = false,
                            Status = "not_started",
                            TotalScore = -1,
                            UserId = "77c46877-537a-4637-bafe-b76b21a2f56e"
                        },
                        new
                        {
                            MockExamId = 20,
                            ExamDate = new DateTime(2025, 3, 25, 11, 39, 50, 158, DateTimeKind.Unspecified).AddTicks(9201),
                            IsPassed = false,
                            Status = "not_started",
                            TotalScore = -1,
                            UserId = "77c46877-537a-4637-bafe-b76b21a2f56e"
                        });
                });

            modelBuilder.Entity("MotorcycleLicenseTrainingAPI.Model.MockExamAnswer", b =>
                {
                    b.Property<int>("MockExamAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MockExamAnswerId"), 1L, 1);

                    b.Property<int?>("AnswerId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("MockExamId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("MockExamAnswerId");

                    b.HasIndex("AnswerId");

                    b.HasIndex("MockExamId");

                    b.HasIndex("QuestionId");

                    b.ToTable("MockExamAnswer");

                    b.HasData(
                        new
                        {
                            MockExamAnswerId = 1,
                            AnswerId = 5,
                            IsCorrect = true,
                            MockExamId = 12,
                            QuestionId = 1
                        },
                        new
                        {
                            MockExamAnswerId = 2,
                            AnswerId = 11,
                            IsCorrect = false,
                            MockExamId = 12,
                            QuestionId = 2
                        },
                        new
                        {
                            MockExamAnswerId = 3,
                            AnswerId = 5,
                            IsCorrect = true,
                            MockExamId = 18,
                            QuestionId = 1
                        },
                        new
                        {
                            MockExamAnswerId = 4,
                            AnswerId = 12,
                            IsCorrect = false,
                            MockExamId = 18,
                            QuestionId = 2
                        });
                });

            modelBuilder.Entity("MotorcycleLicenseTrainingAPI.Model.PracticeHistory", b =>
                {
                    b.Property<int>("PracticeHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PracticeHistoryId"), 1L, 1);

                    b.Property<int?>("AnswerId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PracticeHistoryId");

                    b.HasIndex("AnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("PracticeHistory");

                    b.HasData(
                        new
                        {
                            PracticeHistoryId = 1,
                            AnswerId = 24,
                            IsCorrect = false,
                            QuestionId = 12,
                            UserId = "77c46877-537a-4637-bafe-b76b21a2f56e"
                        },
                        new
                        {
                            PracticeHistoryId = 2,
                            AnswerId = 21,
                            IsCorrect = true,
                            QuestionId = 11,
                            UserId = "77c46877-537a-4637-bafe-b76b21a2f56e"
                        },
                        new
                        {
                            PracticeHistoryId = 3,
                            AnswerId = 7,
                            IsCorrect = true,
                            QuestionId = 1,
                            UserId = "77c46877-537a-4637-bafe-b76b21a2f56e"
                        },
                        new
                        {
                            PracticeHistoryId = 4,
                            AnswerId = 26,
                            IsCorrect = true,
                            QuestionId = 13,
                            UserId = "77c46877-537a-4637-bafe-b76b21a2f56e"
                        },
                        new
                        {
                            PracticeHistoryId = 5,
                            AnswerId = 33,
                            IsCorrect = false,
                            QuestionId = 14,
                            UserId = "77c46877-537a-4637-bafe-b76b21a2f56e"
                        },
                        new
                        {
                            PracticeHistoryId = 6,
                            AnswerId = 34,
                            IsCorrect = false,
                            QuestionId = 15,
                            UserId = "77c46877-537a-4637-bafe-b76b21a2f56e"
                        },
                        new
                        {
                            PracticeHistoryId = 7,
                            AnswerId = 11,
                            IsCorrect = false,
                            QuestionId = 2,
                            UserId = "77c46877-537a-4637-bafe-b76b21a2f56e"
                        },
                        new
                        {
                            PracticeHistoryId = 8,
                            AnswerId = 12,
                            IsCorrect = false,
                            QuestionId = 3,
                            UserId = "77c46877-537a-4637-bafe-b76b21a2f56e"
                        },
                        new
                        {
                            PracticeHistoryId = 9,
                            AnswerId = 39,
                            IsCorrect = false,
                            QuestionId = 5,
                            UserId = "77c46877-537a-4637-bafe-b76b21a2f56e"
                        });
                });

            modelBuilder.Entity("MotorcycleLicenseTrainingAPI.Model.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsFailing")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Question");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            CategoryId = 7,
                            IsFailing = true,
                            QuestionContent = "Người hành nghề lái xe khi thực hiện tốt việc rèn luyện, nâng cao trách nhiệm, đạo đức nghề nghiệp sẽ thu được kết quả như thế nào?"
                        },
                        new
                        {
                            QuestionId = 2,
                            CategoryId = 7,
                            IsFailing = false,
                            QuestionContent = "Người lái xe vận tải hàng hóa cần thực hiện những nhiệm vụ gì ghi ở dưới đây?"
                        },
                        new
                        {
                            QuestionId = 3,
                            CategoryId = 7,
                            IsFailing = false,
                            QuestionContent = "Người lái xe kinh doanh vận tải cần thực hiện những công việc gì ghi ở dưới đây để thường xuyên rèn luyện nâng cao đạo đức nghề nghiệp?",
                            Reason = "Tín hiệu vàng báo hiệu xe phải dừng trước vạch dừng; nếu đã vượt qua vạch thì được đi tiếp."
                        },
                        new
                        {
                            QuestionId = 4,
                            CategoryId = 7,
                            IsFailing = true,
                            QuestionContent = "Người lái xe và nhân viên phục vụ trên xe ô tô vận tải hành khách phải có những trách nhiệm gì theo quy định được ghi ở dưới đây?",
                            Reason = "Theo quy định, lái xe sử dụng rượu bia sẽ bị phạt hành chính, tước bằng lái, nghiêm trọng có thể truy cứu trách nhiệm hình sự."
                        },
                        new
                        {
                            QuestionId = 5,
                            CategoryId = 7,
                            IsFailing = false,
                            QuestionContent = "Khái niệm về văn hóa giao thông được hiểu như thế nào là đúng?",
                            Reason = "Tín hiệu vàng yêu cầu người lái xe dừng lại trước vạch dừng, trừ khi đã vượt qua vạch thì được tiếp tục đi."
                        },
                        new
                        {
                            QuestionId = 11,
                            CategoryId = 9,
                            ImageUrl = "https://lythuyet.onthigplx.vn/images/onthigplx_vn__q306.webp",
                            IsFailing = false,
                            QuestionContent = "Biển nào cấm ô tô tải?",
                            Reason = "Không có"
                        },
                        new
                        {
                            QuestionId = 12,
                            CategoryId = 6,
                            IsFailing = false,
                            QuestionContent = "Phần của đường bộ được sử dụng cho các phương tiện giao thông qua lại là gì?"
                        },
                        new
                        {
                            QuestionId = 13,
                            CategoryId = 6,
                            IsFailing = false,
                            QuestionContent = "“Làn đường” là gì?"
                        },
                        new
                        {
                            QuestionId = 14,
                            CategoryId = 6,
                            IsFailing = false,
                            QuestionContent = "Khái niệm “Khổ giới hạn đường bộ” được hiểu như thế nào là đúng?"
                        },
                        new
                        {
                            QuestionId = 15,
                            CategoryId = 6,
                            IsFailing = false,
                            QuestionContent = "Trong các khái niệm dưới đây, “dải phân cách” được hiểu như thế nào là đúng?"
                        },
                        new
                        {
                            QuestionId = 16,
                            CategoryId = 9,
                            ImageUrl = "https://thibanglaixe24h.net/wp-content/uploads/2020/08/bien-1.png",
                            IsFailing = false,
                            QuestionContent = "Biển báo hiệu có dạng hình tròn, viền đỏ, nền trắng, trên nền có hình vẽ hoặc chữ số, chữ viết màu đen là loại biển gì dưới đây?",
                            Reason = "Biển cấm: vòng tròn đỏ."
                        },
                        new
                        {
                            QuestionId = 17,
                            CategoryId = 9,
                            ImageUrl = "https://thibanglaixe24h.net/wp-content/uploads/2020/08/bien-2.png",
                            IsFailing = false,
                            QuestionContent = "Biển báo hiệu có dạng tam giác đều, viền đỏ, nền màu vàng, trên có hình vẽ màu đen là loại biển gì dưới đây?"
                        });
                });

            modelBuilder.Entity("MotorcycleLicenseTrainingAPI.Model.TrafficSign", b =>
                {
                    b.Property<int>("TrafficSignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrafficSignId"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrafficSignContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrafficSignTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrafficSignId");

                    b.HasIndex("CategoryId");

                    b.ToTable("TrafficSign");

                    b.HasData(
                        new
                        {
                            TrafficSignId = 1,
                            CategoryId = 1,
                            ImageUrl = "https://lh4.googleusercontent.com/proxy/p-X43Y8E4jtza7YzFM6FbBDmQY2yMWKK6ZX5EvRToCqk1B9z79nPcmhw109LJJeRvf-iSkLQPhnUoLV1pu22cPNP_4o",
                            TrafficSignContent = "Để báo cấm các loại xe quay đầu (theo kiểu chữ U). Chiều mũi tên phù hợp với chiều cấm quay đầu xe. Biển số P124a có hiệu lực cấm các loại xe (có giới và thổ sơ) trừ các xe được ưu tiên theo quy định. Biển không có giá trị cấm rẽ trái để đi sang hướng đường khác.",
                            TrafficSignTitle = "Biển số P.124a \"Cấm quay đầu xe\""
                        },
                        new
                        {
                            TrafficSignId = 2,
                            CategoryId = 1,
                            ImageUrl = "https://bizweb.dktcdn.net/100/352/036/files/bien-bao-105.jpg?v=1575706005214",
                            TrafficSignContent = "Để báo đường cấm các loại xe có giới và xe máy đi qua.",
                            TrafficSignTitle = "Biển số P105 \"Cấm xe ô tô và xe máy\""
                        },
                        new
                        {
                            TrafficSignId = 3,
                            CategoryId = 1,
                            ImageUrl = "https://myanhsafety.com.vn/image/cache/catalog/bien-bao-giao-thong-duong-cam-p-101-1-500x500.jpg",
                            TrafficSignContent = "Để báo đường cấm các loại phương tiện đi lại cả hai hướng, trừ các xe được ưu tiên theo quy định.",
                            TrafficSignTitle = "Biển số P101 \"Đường cấm\""
                        },
                        new
                        {
                            TrafficSignId = 4,
                            CategoryId = 1,
                            ImageUrl = "https://bizweb.dktcdn.net/thumb/grande/100/352/036/products/22578292-db52d-jpeg.jpg?v=1600507890367",
                            TrafficSignContent = "Để báo đường cấm các loại xe (có giới và thổ sơ) đi vào theo chiều đặt biển, trừ các xe được ưu tiên theo quy định. Người đi bộ được phép đi trên vỉa hè hoặc lề đường.",
                            TrafficSignTitle = "Biển số P102 \"Cấm đi ngược chiều\""
                        },
                        new
                        {
                            TrafficSignId = 6,
                            CategoryId = 1,
                            ImageUrl = "https://giaothongmiennam.com/uploads/source/loaibienbao/103a.jpg",
                            TrafficSignContent = "Để báo đường cấm các loại xe có giới kể cả xe máy 3 bánh có thùng đi qua, trừ xe máy 2 bánh, xe gắn máy và các xe được ưu tiên theo quy định.",
                            TrafficSignTitle = "Biển số P103a \"Cấm xe ô tô\""
                        },
                        new
                        {
                            TrafficSignId = 7,
                            CategoryId = 3,
                            ImageUrl = "https://bizweb.dktcdn.net/thumb/grande/100/352/036/products/bien-bao-401.jpg?v=1600847944553",
                            TrafficSignContent = "Biểu thị ưu tiên cho các phương tiện trên đường có đặt biển này được đi trước.",
                            TrafficSignTitle = "Biển số I.401 \"Bắt đầu đường ưu tiên\""
                        },
                        new
                        {
                            TrafficSignId = 8,
                            CategoryId = 3,
                            ImageUrl = "https://bizweb.dktcdn.net/thumb/grande/100/352/036/products/bien-bao-402.jpg?v=1600846599747",
                            TrafficSignContent = "Biểu thị hết đoạn đường quy định là ưu tiên.",
                            TrafficSignTitle = "Biển số I.402 \"Hết đoạn đường ưu tiên\""
                        },
                        new
                        {
                            TrafficSignId = 9,
                            CategoryId = 3,
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-81QbPq3MXpSKC9-L1J8Sromeeo2jQRxzYw&s",
                            TrafficSignContent = "Chỉ lối rẽ vào đường cụt.",
                            TrafficSignTitle = "Biển số I.405a \"Đường cụt\""
                        },
                        new
                        {
                            TrafficSignId = 10,
                            CategoryId = 3,
                            ImageUrl = "https://lh5.googleusercontent.com/proxy/R2QonNrldpzKmuP0W4wWKziXU4Yb5R08kL3XBFfzOuHwsmJm79K3pnfFZ8XqV-XIZPDV00QIrUcIIYPeEzqPbxITMUE",
                            TrafficSignContent = "Chỉ lối rẽ vào đường cụt.",
                            TrafficSignTitle = "Biển số I.405b \"Đường cụt\""
                        },
                        new
                        {
                            TrafficSignId = 11,
                            CategoryId = 2,
                            ImageUrl = "https://bizweb.dktcdn.net/thumb/grande/100/352/036/products/bien-bao-dung-lai.jpg?v=1599812231573",
                            TrafficSignContent = "Để báo các xe (có giới và thổ sơ) dừng lại.",
                            TrafficSignTitle = "Biển số R122 \"Dừng lại\""
                        },
                        new
                        {
                            TrafficSignId = 12,
                            CategoryId = 2,
                            ImageUrl = "https://bizweb.dktcdn.net/thumb/grande/100/352/036/products/5748397301-jpeg.jpg?v=1599903632117",
                            TrafficSignContent = "Khi đặt biển số R.301a ở trước nơi đường giao nhau thì hiệu lực tác dụng của biển là ở phạm vi khu vực nơi đường giao nhau phía sau biển tức là cấm xe rẽ phải hay rẽ trái. Nếu biển này đặt ở sau nơi đường giao nhau (bắt đầu vào đoạn đường phố) thì hiệu lực tác dụng của biển là từ vị trí đặt biển đến nơi đường giao nhau. Trong trường hợp này cấm rẽ trái và quay đầu trong vùng tác dụng của biển, chỉ cho phép rẽ phải vào cổng nhà hoặc ngõ phố có trên đoạn đường từ nơi đường giao nhau đặt biển đến nơi đường giao nhau tiếp theo.",
                            TrafficSignTitle = "Biển số R.301a \"Hướng đi phải theo\""
                        },
                        new
                        {
                            TrafficSignId = 13,
                            CategoryId = 2,
                            ImageUrl = "https://bizweb.dktcdn.net/thumb/1024x1024/100/352/036/products/1831909bien-hieu-lenh-301e-jpeg.jpg?v=1599903903743",
                            TrafficSignContent = "Nhằm chỉ hướng cho phép xe đi ngang qua nơi đường giao nhau và ngăn chặn hướng đi ngược chiều trên đường phố với đường một chiều. Biển bắt buộc người tham gia giao thông chỉ được phép rẽ phải hoặc rẽ trái ở phạm vi nơi đường giao nhau trước mặt biển.",
                            TrafficSignTitle = "Biển số R.301b \"Hướng đi phải theo\""
                        },
                        new
                        {
                            TrafficSignId = 14,
                            CategoryId = 4,
                            ImageUrl = "https://myanhsafety.com.vn/image/cache/catalog/bien-bao-nguy-hiem-201a-1-0x0.jpg",
                            TrafficSignContent = "Báo trước sắp đến một chỗ ngoặt nguy hiểm vòng bên trái.",
                            TrafficSignTitle = "Biển số W.201a \"Chỗ ngoặt nguy hiểm\""
                        },
                        new
                        {
                            TrafficSignId = 15,
                            CategoryId = 4,
                            ImageUrl = "https://myanhsafety.com.vn/image/cache/catalog/bien-bao-nguy-hiem-201b-500x500.jpg",
                            TrafficSignContent = "Báo trước sắp đến một chỗ ngoặt nguy hiểm vòng bên phải.",
                            TrafficSignTitle = "Biển số W.201b \"Chỗ ngoặt nguy hiểm\""
                        },
                        new
                        {
                            TrafficSignId = 16,
                            CategoryId = 4,
                            ImageUrl = "https://bizweb.dktcdn.net/thumb/grande/100/352/036/products/bien-202.jpg?v=1600248249870",
                            TrafficSignContent = "Báo trước sắp đến hai chỗ ngoặt ngược chiều nhau liên tiếp, ở gần nhau trong đó có ít nhất một chỗ ngoặt nguy hiểm.",
                            TrafficSignTitle = "Biển số W.202a \"Nhiều chỗ ngoặt nguy hiểm liên tiếp\""
                        },
                        new
                        {
                            TrafficSignId = 17,
                            CategoryId = 5,
                            ImageUrl = "https://cdn-i.vtcnews.vn/resize/th/upload/2024/05/03/bien-bao-501-1-15032563.jpg",
                            TrafficSignContent = "Để thông báo chiều dài đoạn đường nguy hiểm hoặc cấm hoặc hạn chế bên dưới một số biển báo nguy hiểm, biển báo cấm hoặc hạn chế.",
                            TrafficSignTitle = "Biển số S.501 \"Phạm vi tác dụng của biển\""
                        },
                        new
                        {
                            TrafficSignId = 18,
                            CategoryId = 5,
                            ImageUrl = "https://sathachmophong.com/wp-content/uploads/2022/12/Bien-so-S.502.webp",
                            TrafficSignContent = "Để thông báo khoảng cách thực tế từ vị trí đặt biển đến đối tượng báo hiệu ở phía trước. Con số trên biển ghi theo đơn vị mét (m) và lấy chân đến hàng chức mét.",
                            TrafficSignTitle = "Biển số S.502 \"Khoảng cách đến đối tượng báo hiệu\""
                        },
                        new
                        {
                            TrafficSignId = 19,
                            CategoryId = 5,
                            ImageUrl = "https://lh5.googleusercontent.com/proxy/R5rT_cBAkJKAsB4nCjDP9xvGAOo1GZ9WLasPUDU2SxD2DaSSxVTWtyaAZ26X_dfqDTxk2d9UjP7eBpsW6PK9tpi88Y0Ra1EPpIUtOOksXw5wxCxM1hHcwxpFxGtsr1Gf-6K4RUQc8m1iKwPMDYw",
                            TrafficSignContent = "Để chỉ hướng tác dụng của biển là hướng vuông góc với chiều đi.",
                            TrafficSignTitle = "Biển số S.503a \"Hướng tác dụng của biển\""
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MotorcycleLicenseTrainingAPI.Model.ApplicationUsers", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MotorcycleLicenseTrainingAPI.Model.ApplicationUsers", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotorcycleLicenseTrainingAPI.Model.ApplicationUsers", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MotorcycleLicenseTrainingAPI.Model.ApplicationUsers", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MockExamQuestion", b =>
                {
                    b.HasOne("MotorcycleLicenseTrainingAPI.Model.MockExam", null)
                        .WithMany()
                        .HasForeignKey("MockExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotorcycleLicenseTrainingAPI.Model.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MotorcycleLicenseTrainingAPI.Model.Answer", b =>
                {
                    b.HasOne("MotorcycleLicenseTrainingAPI.Model.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("MotorcycleLicenseTrainingAPI.Model.MockExam", b =>
                {
                    b.HasOne("MotorcycleLicenseTrainingAPI.Model.ApplicationUsers", "User")
                        .WithMany("MockExams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotorcycleLicenseTrainingAPI.Model.MockExamAnswer", b =>
                {
                    b.HasOne("MotorcycleLicenseTrainingAPI.Model.Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotorcycleLicenseTrainingAPI.Model.MockExam", "MockExam")
                        .WithMany("MockExamAnswers")
                        .HasForeignKey("MockExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotorcycleLicenseTrainingAPI.Model.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("MockExam");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("MotorcycleLicenseTrainingAPI.Model.PracticeHistory", b =>
                {
                    b.HasOne("MotorcycleLicenseTrainingAPI.Model.Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotorcycleLicenseTrainingAPI.Model.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotorcycleLicenseTrainingAPI.Model.ApplicationUsers", "User")
                        .WithMany("PracticeHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotorcycleLicenseTrainingAPI.Model.Question", b =>
                {
                    b.HasOne("MotorcycleLicenseTrainingAPI.Model.Category", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MotorcycleLicenseTrainingAPI.Model.TrafficSign", b =>
                {
                    b.HasOne("MotorcycleLicenseTrainingAPI.Model.Category", "Category")
                        .WithMany("TrafficSigns")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MotorcycleLicenseTrainingAPI.Model.ApplicationUsers", b =>
                {
                    b.Navigation("MockExams");

                    b.Navigation("PracticeHistories");
                });

            modelBuilder.Entity("MotorcycleLicenseTrainingAPI.Model.Category", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("TrafficSigns");
                });

            modelBuilder.Entity("MotorcycleLicenseTrainingAPI.Model.MockExam", b =>
                {
                    b.Navigation("MockExamAnswers");
                });

            modelBuilder.Entity("MotorcycleLicenseTrainingAPI.Model.Question", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
